name: CI
on:
  pull_request:
  push:
    tags:
    branches:
      - 'master'
jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: Upload image
        id: upload-image-0
        uses: McCzarny/upload-image@v1.0.0
        if: github.event_name == 'pull_request'
        with:
          path: images/0.png
          uploadMethod: imgbb
          apiKey: '${{ secrets.IMGBB_API_KEY }}'
      - name: 'Comment PR'
        uses: actions/github-script@0.3.0
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.TOKEN_GITHUB }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
            github.issues.createComment({ issue_number, owner, repo, body: 'Uploaded image:\n![0](${{steps.upload-image-0.outputs.url}})'});
