name: CI
on:
  pull_request_target:
  push:
    tags:
    branches:
      - 'main'
jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Comment PR'
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request_target'
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 testing commenting, changesss'
            })
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - run: ./build.sh
      - run: |
          git log --graph | cat
      - name: Upload image
        id: upload-image-0
        uses: McCzarny/upload-image@v1.0.0
        if: github.event_name == 'pull_request_target'
        with:
          path: images/0.png
          uploadMethod: imgbb
          apiKey: '${{ secrets.IMGBB_API_KEY }}'
      - name: 'Comment PR with image'
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request_target'
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Uploaded image:\n![0](${{steps.upload-image-0.outputs.url}})'
            })
